defaultPortal:
  portalId: YOUR_PORTAL_ID
  authType: oauth2
  authToken: YOUR_AUTH_TOKEN

portals:
  - portalId: YOUR_PORTAL_ID
    name: "Orion Beta Portal"
    authType: oauth2
    authToken: YOUR_AUTH_TOKEN
